### PR TITLE
Ctrl-Click on post title

### PR DESCRIPTION
**Pull request by sboo**
Hi 

I added the possibility to ctrl-click on the post-title to open the url directly instead of going to the detail page first.

### CODE REVIEW

**Comment by sboo** [comment]
Hi,

What do you think, does it make sense to mark the post as read when ctrl-clicking it? If so, I can fix that.

Cheers,
Ramon

**Comment by aboustayyef** [comment]
I did think about that but I concluded it's not the right approach. I usually cmd-click when I want to check something in the background without affecting my state. (BTW if you noticed, I expanded your contribution to work with Macs and on the paragraph preview as well)

**Comment by sboo** [comment]
Yeah I agree, I tested it out and it didn't feel right.  I just noticed your updates, I'll pull them now :)
Another thing I've been playing with is to fetch posts automatically again on `window.onfocus` and it's been a x minutes since the last fetchPostList(). Like that you don't need a page refresh. 

Is that something you'd like to have implemented in your app?

**Comment by aboustayyef** [comment]
I'd like to implement an auto refresh, but I don't think window.onfocus is the right way to go about it. I Was thinking more of a time based approach, since the backend crawls the feeds every 10 minutes, so refreshing every time a window.onfocus happens seems wasteful.

**Comment by sboo** [comment]
That's why I thought to only do it onfocus and after x minutes, 10 in this case. The reason why I thought of the combo with onfocus because I think it could be distracting if a refresh happens while looking at the list.

**Comment by aboustayyef** [comment]
Sounds like a plan then! But I'm thinking of not hard-coding the 10 mins. Maybe we want to change it later or some users want more/less frequent crawling. How about we add it as a setting in the .env file with a default of 10?

**Comment by sboo** [comment]
Sounds like a good idea! Do you want me to get started with it or do you want to do it yourself?

**Comment by aboustayyef** [comment]
Please be my guest... (thanks for help)

**Comment by sboo** [comment]
No worries, I'll have a go at it then :)

**Comment by aboustayyef** [comment]
Just remember that the .env file is not part of the repo. So you need to make the change in .env.example as well.

**Comment by sboo** [comment]
Of course! Don't worry, I work a lot with Laravel at work, it's my day job

**Comment by aboustayyef** [comment]
Great. Looking forward to learn a thing or two from you..

**Comment by aboustayyef** [comment]
Forgot to mention. After you make a pull, you need to do a migration and composer install. (But check you have php 7.1 or higher)

**Comment by sboo** [comment]
yeah, I noticed. I'll updated composer.json to reflect that too

**Pull request merged**
