### PR TITLE
Variable refresh interval  and autorefresh

### PR DESCRIPTION
**Pull request by sboo**
Check the changes.  Let me know if it's okay for you, or if you want me to change something

### CODE REVIEW

**Comment by sboo** [comment]
HOld on, there's a mistace in the->cron()

**Comment by aboustayyef** [comment]
I’m on the road now, but I checked the code on my phone and everything looks ok. (Thanks for changing the app name. I completely missed that!) 
Did you test the code?

I was thinking of adding some validation logic to the refresh rate (not less than 0, not more than 60) what do you think?

**Comment by sboo** [comment]
That could be nice, but I figured if someone wants to mess up their own installation it's their own fault.
Yeah I have it running here locally, otherwise I wouldn't push it :D

**Comment by aboustayyef** [comment]
Cool. Will merge ASAP. After that, I’ll add a feature that is made possible by your addition: changing the document’s title to “(unread_count) title” so the app can be kept in a background tab.

**Comment by sboo** [comment]
Cool, that's a great idea!

**Pull request merged**
